{"version":3,"sources":["../../src/koa/18.js"],"names":["Koa","require","app","handler","err","ctx","next","response","status","statusCode","type","body","emit","main","throw","on","console","log","message","use","listen"],"mappings":";;;;;;;;;;;;AAAA;;;;;;AAMA,IAAMA,MAAMC,QAAQ,KAAR,CAAZ;AACA,IAAMC,MAAM,IAAIF,GAAJ,EAAZ;;AAEA,IAAMG;AAAA,sFAAU,iBAAOC,GAAP,EAAYC,GAAZ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,mBAENC,MAFM;;AAAA;AAAA;AAAA;;AAAA;AAAA;AAAA;;AAIZD,gBAAIE,QAAJ,CAAaC,MAAb,GAAsB,YAAIC,UAAJ,IAAkB,YAAID,MAAtB,IAAgC,GAAtD;AACAH,gBAAIE,QAAJ,CAAaG,IAAb,GAAoB,MAApB;AACAL,gBAAIE,QAAJ,CAAaI,IAAb,GAAoB,uDAApB;AACAN,gBAAIH,GAAJ,CAAQU,IAAR,CAAa,OAAb,eAA2BP,GAA3B;;AAPY;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,GAAV;;AAAA;AAAA;AAAA;AAAA,GAAN;;AAWA,IAAMQ,OAAO,SAAPA,IAAO,MAAO;AAClBR,MAAIS,KAAJ,CAAU,GAAV;AACD,CAFD;;AAIAZ,IAAIa,EAAJ,CAAO,OAAP,EAAgB,eAAO;AACrBC,UAAQC,GAAR,CAAY,cAAZ,EAA4Bb,IAAIc,OAAhC;AACAF,UAAQC,GAAR,CAAYb,GAAZ;AACD,CAHD;;AAKAF,IAAIiB,GAAJ,CAAQhB,OAAR;AACAD,IAAIiB,GAAJ,CAAQN,IAAR;;AAEAX,IAAIkB,MAAJ,CAAW,IAAX","file":"18.js","sourcesContent":["/**\r\n !c 释放error事件\r\n ?c 需要注意的是，如果错误被try...catch捕获，就不会触发error事件，\r\n ?c 必须调用 ctx.app.emit() 手动释放error事件，才能让监听函数生效\r\n */\r\n\r\nconst Koa = require('koa')\r\nconst app = new Koa()\r\n\r\nconst handler = async (err, ctx) => {\r\n  try {\r\n    await next()\r\n  } catch (err) {\r\n    ctx.response.status = err.statusCode || err.status || 500\r\n    ctx.response.type = 'html'\r\n    ctx.response.body = '<p>Something wrong, please contact administrator.</p>'\r\n    ctx.app.emit('error', err, ctx);\r\n  }\r\n}\r\n\r\nconst main = ctx => {\r\n  ctx.throw(500)\r\n}\r\n\r\napp.on('error', err => {\r\n  console.log('logger error', err.message)\r\n  console.log(err)\r\n})\r\n\r\napp.use(handler)\r\napp.use(main)\r\n\r\napp.listen(3000)"]}